fix filer address parsing
When `-master` is not set but master address exists in config
`-filer` option is ignored.

If in this case filer address exists in shell.toml too it for some reason
icorrectly parsed and causes errors like

```

dial tcp: lookup 127.0.0.1:1111.1112,127.0.0.2: no such host

error: rpc error: code = Unimplemented desc = unknown service filer_pb.SeaweedFiler

transport: Error while dialing: dial tcp 127.0.0.1:11111: connect: connection refused
```

Note: I use non default grpc ports

Only working combinations I found:
1. both -master and -filer provided through command line / env
2. master address in config, no filer adress (so it auto-discovered)